language: android
android:
        components:
                - tools
                - platform-tools
                - build-tools-28.0.0
                - extra-android-support
                - extra-google-m2repository
                - extra-android-m2repository
                 # Specify at least one system image,
                 # if you need to run emulator(s) during your tests
                - sys-img-armeabi-v7a-android-26
                - sys-img-armeabi-v7a-android-17
script:
    - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
before_install:
    - yes | sdkmanager "platforms;android-28"
    - chmod +x gradlew
branches:
        only:
                - master
cache:
        directories:
                    # Android SDK
                    - $HOME/android-sdk-dl
                    - $HOME/android-sdk