language: android
jdk: oraclejdk8
android:
    components:
      - tools
      - platform-tools
      - build-tools-28.0.0
      - android-28
      - android-22 #for the emulator
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      # we need the system image here if we are going to run an emulator later
      - sys-img-armeabi-v7a-android-22

# magic for launching an emulator for running the tests
# although I managed to make it work, despite what the documents say
# Warning: At the moment, these steps are not fully supported by Travis CI Android builder.
before_script:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
# what commands should we run
script:
- ./gradlew build #build it
- ./gradlew connectedCheck #run tests in androidTest folder
#- ./gradlew check #run unit tests
before_install:
#prevents a validation error for licenses
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
branches:
        only:
                - master
cache:
        directories:
                    # Android SDK
                    - $HOME/android-sdk-dl
                    - $HOME/android-sdk